// lib/data.ts
import { MenuItem, Category, Testimonial, SpecialOffer, Event } from "@/types";

export const categories: Category[] = [
  { id: "1", name: "Appetizers", description: "Start your meal right" },
  { id: "2", name: "Main Course", description: "Hearty and satisfying" },
  { id: "3", name: "Desserts", description: "Sweet endings" },
  { id: "4", name: "Beverages", description: "Refresh yourself" },
];

export const menuItems: MenuItem[] = [
  {
    id: "1",
    name: "Bruschetta",
    description: "Grilled bread topped with fresh tomatoes, garlic, and basil",
    price: 8.99,
    image: "/images/bruschetta.jpg",
    category: "Appetizers",
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: "2",
    name: "Grilled Salmon",
    description: "Fresh Atlantic salmon with lemon butter sauce and vegetables",
    price: 24.99,
    image: "/images/salmon.jpg",
    category: "Main Course",
    isPopular: true,
  },
  {
    id: "3",
    name: "Ribeye Steak",
    description: "12oz prime ribeye with garlic mashed potatoes",
    price: 34.99,
    image: "/images/steak.jpg",
    category: "Main Course",
  },
  {
    id: "4",
    name: "Spicy Pasta Arrabbiata",
    description: "Penne pasta in spicy tomato sauce with fresh herbs",
    price: 16.99,
    image: "/images/pasta.jpg",
    category: "Main Course",
    isVegetarian: true,
    isSpicy: true,
  },
  {
    id: "5",
    name: "Tiramisu",
    description: "Classic Italian dessert with espresso and mascarpone",
    price: 9.99,
    image: "/images/tiramisu.jpg",
    category: "Desserts",
    isPopular: true,
  },
  {
    id: "6",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center",
    price: 10.99,
    image: "/images/lava-cake.jpg",
    category: "Desserts",
  },
  {
    id: "7",
    name: "Butter Chicken",
    description: "Tender chicken in a creamy, tomato-based butter sauce",
    price: 18.99,
    image: "/images/butter-chicken.jpg",
    category: "Main Course",
    isPopular: true,
  },
  {
    id: "8",
    name: "Paneer Tikka",
    description: "Marinated cottage cheese cubes grilled in a tandoor",
    price: 14.99,
    image: "/images/paneer-tikka.jpg",
    category: "Appetizers",
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: "9",
    name: "Lamb Rogan Josh",
    description: "Slow-cooked lamb in a rich aromatic Kashmiri gravy",
    price: 22.99,
    image: "/images/lamb-rogan.jpg",
    category: "Main Course",
    isSpicy: true,
    isPopular: true,
  },
  {
    id: "10",
    name: "Garlic Naan",
    description: "Soft leavened bread with garlic and fresh coriander",
    price: 4.99,
    image: "/images/naan.jpg",
    category: "Beverages", // Or add a 'Sides' category
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: "11",
    name: "Gulab Jamun",
    description: "Deep-fried milk dumplings soaked in saffron sugar syrup",
    price: 7.99,
    image: "/images/gulab-jamun.jpg",
    category: "Desserts",
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: "12",
    name: "Crispy Calamari",
    description: "Lightly breaded squid rings served with spicy marinara and lemon aioli",
    price: 13.99,
    image: "/images/calamari.jpg",
    category: "Appetizers",
    isPopular: false,
  },
  {
    id: "13",
    name: "Vegetable Biryani",
    description: "Fragrant basmati rice cooked with seasonal vegetables and aromatic spices",
    price: 15.99,
    image: "/images/veg-biryani.jpg",
    category: "Main Course",
    isVegetarian: true,
  },
  {
    id: "14",
    name: "Chicken Tikka Masala",
    description: "Roasted marinated chicken chunks in a spiced, creamy orange-colored sauce",
    price: 19.99,
    image: "/images/chicken-tikka.jpg",
    category: "Main Course",
    isPopular: true,
  },
  {
    id: "15",
    name: "Malai Kofta",
    description: "Potato and paneer dumplings simmered in a rich, creamy cashew gravy",
    price: 17.99,
    image: "/images/malai-kofta.jpg",
    category: "Main Course",
    isVegetarian: true,
  },
  {
    id: "16",
    name: "Mango Lassi",
    description: "Traditional chilled yogurt drink blended with sweet Alphonso mangoes",
    price: 5.99,
    image: "/images/mango-lassi.jpg",
    category: "Beverages",
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: "17",
    name: "Masala Chai",
    description: "Indian tea brewed with ginger, cardamom, and aromatic spices",
    price: 3.99,
    image: "/images/masala-chai.jpg",
    category: "Beverages",
    isVegetarian: true,
  },
  {
    id: "18",
    name: "Jeera Rice",
    description: "Basmati rice tempered with cumin seeds and fresh ghee",
    price: 6.99,
    image: "/images/jeera-rice.jpg",
    category: "Sides",
    isVegetarian: true,
  },
  {
    id: "19",
    name: "Truffle Fries",
    description: "Crispy golden fries tossed in truffle oil and parmesan cheese",
    price: 7.99,
    image: "/images/truffle-fries.jpg",
    category: "Sides",
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: "20",
    name: "Pista Kulfi",
    description: "Traditional Indian ice cream flavored with saffron and pistachios",
    price: 6.99,
    image: "/images/kulfi.jpg",
    category: "Desserts",
    isVegetarian: true,
  }
];

export const specialOffers: SpecialOffer[] = [
  {
    id: "1",
    title: "Family Feast Bundle",
    description: "Perfect for family gatherings! Includes 2 appetizers, 4 main courses, 2 desserts, and a bottle of house wine.",
    discount: "25% OFF",
    originalPrice: 159.99,
    offerPrice: 119.99,
    image: "/images/family-feast.jpg",
    validUntil: "2024-12-31",
    terms: "Valid for dine-in only. Cannot be combined with other offers.",
    badge: "Best Value",
    type: "combo",
  },
  {
    id: "2",
    title: "Lunch Express Special",
    description: "Quick and delicious! Choose any pasta or salad with a drink. Perfect for your lunch break.",
    discount: "30% OFF",
    originalPrice: 24.99,
    offerPrice: 17.49,
    image: "/images/lunch-special.jpg",
    validUntil: "2024-12-31",
    terms: "Available Monday-Friday, 11AM-3PM only.",
    badge: "Lunch Deal",
    type: "discount",
  },
  {
    id: "3",
    title: "Happy Hour",
    description: "Enjoy half-price appetizers and $5 cocktails every weekday evening. The perfect way to unwind!",
    discount: "50% OFF",
    image: "/images/happy-hour.jpg",
    validUntil: "2024-12-31",
    terms: "Monday-Friday, 4PM-7PM. Bar area only.",
    badge: "Daily Special",
    type: "happy-hour",
  },
  {
    id: "4",
    title: "Seasonal Truffle Menu",
    description: "Experience our limited-time truffle-infused dishes. Fresh black truffles from Italy in every bite.",
    image: "/images/truffle-menu.jpg",
    validUntil: "2024-03-31",
    badge: "Limited Time",
    type: "seasonal",
  },
];

export const upcomingEvents: Event[] = [
  {
    id: "1",
    title: "Wine Tasting Evening",
    description: "Join our sommelier for an exclusive evening featuring premium Italian wines paired with artisan cheeses and charcuterie.",
    date: "2024-02-15",
    time: "7:00 PM - 10:00 PM",
    image: "/images/wine-tasting.jpg",
    price: 75,
    spotsLeft: 12,
    tags: ["Wine", "Tasting", "Premium"],
  },
  {
    id: "2",
    title: "Valentine's Day Special",
    description: "Celebrate love with our romantic 5-course dinner. Live music, candlelit ambiance, and a complimentary champagne toast.",
    date: "2024-02-14",
    time: "6:00 PM - 11:00 PM",
    image: "/images/valentines.jpg",
    price: 150,
    spotsLeft: 8,
    tags: ["Romantic", "Special Menu", "Live Music"],
  },
  {
    id: "3",
    title: "Cooking Masterclass",
    description: "Learn to make authentic Italian pasta from scratch with Chef Marco. Includes recipe booklet and wine.",
    date: "2024-02-20",
    time: "2:00 PM - 5:00 PM",
    image: "/images/cooking-class.jpg",
    price: 95,
    spotsLeft: 6,
    tags: ["Cooking", "Interactive", "Learn"],
  },
  {
    id: "4",
    title: "Live Jazz Sundays",
    description: "Enjoy live jazz music every Sunday during brunch. Featuring local artists and our special brunch menu.",
    date: "2024-02-18",
    time: "11:00 AM - 3:00 PM",
    image: "/images/jazz-brunch.jpg",
    isFree: true,
    tags: ["Live Music", "Brunch", "Family"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    rating: 5,
    comment: "Amazing food and atmosphere! The steak was cooked to perfection.",
    avatar: "/images/avatar1.jpg",
  },
  {
    id: "2",
    name: "Michael Chen",
    rating: 5,
    comment: "Best Italian restaurant in town. The tiramisu is a must-try!",
    avatar: "/images/avatar2.jpg",
  },
  {
    id: "3",
    name: "Emily Davis",
    rating: 4,
    comment: "Great service and delicious food. Will definitely come back!",
    avatar: "/images/avatar3.jpg",
  },
];

export const restaurantInfo = {
  name: "The Taste Avenue",
  tagline: "Authentic Indian Cuisine",
  description: "Experience the finest Indian cuisine in an elegant setting",
  address: "123 Gourmet Street, Food City, FC 12345",
  phone: "(555) 123-4567",
  email: "info@labellacucina.com",
  hours: {
    weekdays: "11:00 AM - 10:00 PM",
    weekends: "10:00 AM - 11:00 PM",
  },
};